# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dockerrockstarapi:
    image: dvdmrk/d4dd-api:latest
    deploy:  
      replicas: 10
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports:
      - target: 5000
        published: 5000
    networks:
      - api-net

  dockerrockstarweb:
    image: dvdmrk/d4dd-web:latest
    build:
      context: DockerRockstarSpa
      dockerfile: Dockerfile
    ports:
      - 8082:80

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8084:8080
  
  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "P@$$$$w0rd"
      POSTGRES_DB: "DockerRockstarDB"
    volumes: 
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:

networks:
  api-net: